### ISSUE TITLE
RDF support

### ISSUE THREAD

**Issue by inigoserna** [timendum/feedendum#1]
Hi,
I've just discovered `feedendum` and I like it a lot, I'm using it to replace `feedparser` on an old application I wrote, the speed difference is notable.
Anyway, I missed RDF (RSS 1.0) support, so I've coded the support to parse and write such feeds.
I'll be really pleased if you could include it in your package (and thus I could simplify mine) and release a new version in pypi.
Are you interested?
The `rdf.py` is completed and working but I should update documentation, add tests, etc.
Do you prefer a pull requests or the plain file and diffs? (I'm old enough to prefer diffs, but you decide).
Thanks for this library!

**Comment by timendum** [comment]
Hi,
feel free to send the diff or create the pull request.

I will work on it on a different branch, add tests and so on, and hopefully merge.

**Comment by inigoserna** [comment]
Hello again,

I've prepared a patch against last commit in this repo.

Some comments:
- I've tried to keep your coding style and naming
- I've adapted documentation and import stuff 
- I've tested the code with all (5) the RDF feeds from my personal OPML file
- I've written some tests, they pass, but there is the bug I mention below 
- I needed to add a different `NS["rdf"]` in `rdf.py`, hiding the original value
- The `generate` function has a bug I can't resolve: it generates 2 `channel` entries

[feedendum-rdf.patch.txt](https://github.com/timendum/feedendum/files/12061273/feedendum-rdf.patch.txt)

**Comment by timendum** [comment]
Hi,
i've worked on the [rdf branch](https://github.com/timendum/feedendum/tree/rdf), can you have a look?

Thanks for the style, I've found it very easy to follow.

I've renamed the `NS["rds"]` to `NS["rdsns"]` to avoid collision and also solved the double channel entries.

I'm also considering using `add_content_element` for the `description` element, as it looks like used most of the time for HTML, do you confirm?

**Comment by inigoserna** [comment]
Hi, and sorry for the late response, I just came back from holidays.

I've seen you have already released a v0.3.0 with the RDF support in.

I've upgraded the package via pip but unfortunately the installed package has no *.py files, so the import fails.

I've also noted you migrated to pyproject.toml. As I'm not familiar with this format, I've searched some help from internet and done the steps mentioned in ¹ to tun `python setup.py install`, but the installed package doesn't contain the *py files with the code either. 

¹ https://stackoverflow.com/questions/62983756/what-is-pyproject-toml-file-for

**Comment by inigoserna** [comment]
Adding a line with an explicit `include = ["feedendum"]` in `[tool.setuptools.packages.find]` solves the problem for me.

Btw, RDF code seems to works correctly.

**Comment by timendum** [comment]
I've uploaded a 0.3.0.1 package on pypi and it looks good to me.

Solved switching to `hatch` as a building tool.

**Comment by timendum** [comment]
Heads up: v0.3.1 produce a slightly different RDF output:

- no id element (it's not in the specification)
- added attributed to channel element

This should be hopefully more correct, but let me know if there are any issues.

**Comment by inigoserna** [comment]
[Excuse for the late response, got some health problems in the family]

v0.3.1 works perfectly here. Thanks a lot.

**Comment by inigoserna** [comment]
RDF  support implemented. Closing this issue.

**Comment by timendum** [comment]
I'm sorry to read that, I hope it's all solved for the good.
